name: Checks
on:
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:
    types: [checks_requested]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test

      - name: Check for uncommitted changes
        run: |
          git diff --exit-code || (echo "::error::Detected uncommitted changes after testing, run locally and update coverage" && exit 1)

  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: |
          npm run format:check || (echo "::error::Code formatting issues found. Run 'npm run format' locally and commit the results" && exit 1)
